sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - ruby-head
  - 2.2
  - 2.1
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    - tj+travis_baf@a13.fr
