image: freebsd/latest
packages:
  - devel/ruby-gems

sources:
  - https://git.sr.ht/~tjj/baf

triggers:
  - action: email
    condition: failure
    to: Thibault Jouan <tj+sirhat_baf@a13.fr>

tasks:
  - install: |
      cd baf
      . .builds/env.sh
      ./bin/ci/install.sh
  - test: |
      cd baf
      . .builds/env.sh
      ./bin/ci/test.sh
